# $RuOBSD: Makefile,v 1.1 2004/04/24 03:58:39 form Exp $

LIB=	cnupm
SRCS=	cnupm_daemon.c cnupm_family.c cnupm_pidfile.c cnupm_progname.c
SRCS+=	cnupm_protocol.c cnupm_restrict.c cnupm_ulval.c cnupm_version.c

NOLINT=
NOPIC=
NOPROFILE=

.include "${.CURDIR}/../BSDosdefs.inc"

install:

.include <bsd.lib.mk>
